feat: namespace refactoring (#53)
* chore: updated git ignore

* fix: minor policy updates for nested stacks

* feat: updated namespace definition. Namespace only gets set once. No longer creating one for each stage as this doesn't change.
Created new  templates for shared infra, splitting namespaces from images bucket.
Updated templates with references to SSM parameters.

* fix: standardizing on double quotes for yaml strings

* fix: missed updates and sync with cookiecutters

---------

Co-authored-by: Kevin Chan <kevinwochan@gmail.com>

diff --git a/unicorn_shared/Makefile b/unicorn_shared/Makefile
--- a/unicorn_shared/Makefile
+++ b/unicorn_shared/Makefile
@@ -1,23 +1,34 @@
-#### Global Variables
-stackName		:= $(shell yq -oy '.default.global.parameters.stack_name' samconfig.yaml)
+.ONESHELL:
 
+ENVIRONMENTS = local dev prod
 
-#### Build/Deploy Tasks
-build:
-	sam build -c $(DOCKER_OPTS)
+.PHONY: deploy-namespaces deploy-images delete-namespaces delete-images
 
-deps:
+deploy-namespaces:  ## Deploys global Unicorn Properties namespaces for all Stages
+	aws cloudformation create-stack --stack-name uni-prop-namespaces --template-body file://uni-prop-namespaces.yaml --capabilities CAPABILITY_AUTO_EXPAND
 
+deploy-images:  	## Deploys shared images stack for local dev prod stages
+	@for env in $(ENVIRONMENTS); do \
+		stage=$$env; \
+		if ! aws cloudformation describe-stacks --stack-name "uni-prop-$$env-images" >/dev/null 2>&1; then \
+			echo "Creating shared images stack for $$env environment"; \
+			aws cloudformation create-stack \
+				--stack-name "uni-prop-$$env-images" \
+				--template-body file://uni-prop-images.yaml \
+				--parameters ParameterKey=Stage,ParameterValue=$$stage \
+				--capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND || echo "Stack creation failed!"; \
+		fi; \
+	done
 
-deploy: build
-	sam deploy
+delete-namespaces: ## Depletes Unicorn Properties namespaces
+	aws cloudformation delete-stack --stack-name uni-prop-namespaces
 
-
-#### Tests
-test: 
-
-
-
-#### Utilities
-ci_init:
-	pnpm i
+delete-images: ## Deletes all shared images stacks
+	@for env in $(ENVIRONMENTS); do \
+			stage=$$env; \
+			if aws cloudformation describe-stacks --stack-name "uni-prop-$$env-images" >/dev/null 2>&1; then \
+				echo "Deleting shared images stack for $$env environment"; \
+				aws cloudformation delete-stack \
+					--stack-name "uni-prop-$$env-images"; \
+			fi; \
+		done
